"""initial schema with research workflow

Revision ID: 221e630d3f7b
Revises:
Create Date: 2026-06-28 16:51:40.551748
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers
revision: str = "221e630d3f7b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entity_relations",
        sa.Column(
            "source_entity_type",
            sa.String(length=50),
            nullable=False,
            comment="源实体类型: person, book, version, passage",
        ),
        sa.Column(
            "source_entity_id",
            sa.String(length=36),
            nullable=False,
            comment="源实体 ID",
        ),
        sa.Column(
            "target_entity_type",
            sa.String(length=50),
            nullable=False,
            comment="目标实体类型: person, book, version, passage",
        ),
        sa.Column(
            "target_entity_id",
            sa.String(length=36),
            nullable=False,
            comment="目标实体 ID",
        ),
        sa.Column(
            "relation_type",
            sa.String(length=50),
            nullable=False,
            comment="关系类型: authored, compiled, commented_on, cited_in, studied, compared, referenced, related_to",
        ),
        sa.Column("description", sa.Text(), nullable=True, comment="关系说明"),
        sa.Column("evidence", sa.Text(), nullable=True, comment="关系依据/证据"),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_entity_relations_source_entity_id"),
        "entity_relations",
        ["source_entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entity_relations_source_entity_type"),
        "entity_relations",
        ["source_entity_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entity_relations_target_entity_id"),
        "entity_relations",
        ["target_entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entity_relations_target_entity_type"),
        "entity_relations",
        ["target_entity_type"],
        unique=False,
    )
    op.create_table(
        "images",
        sa.Column(
            "related_entity_type",
            sa.String(length=50),
            nullable=False,
            comment="关联实体类型 (book, version, passage, person, paper)",
        ),
        sa.Column(
            "related_entity_id",
            sa.String(length=36),
            nullable=False,
            comment="关联实体 ID",
        ),
        sa.Column("url", sa.String(length=2000), nullable=False, comment="图片 URL"),
        sa.Column("caption", sa.Text(), nullable=True, comment="图片说明"),
        sa.Column("source", sa.String(length=500), nullable=True, comment="图片来源"),
        sa.Column(
            "license_info", sa.String(length=500), nullable=True, comment="授权信息"
        ),
        sa.Column("order", sa.Integer(), nullable=True, comment="排序"),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_images_related_entity_id"),
        "images",
        ["related_entity_id"],
        unique=False,
    )
    op.create_table(
        "papers",
        sa.Column("title", sa.String(length=1000), nullable=False, comment="论文标题"),
        sa.Column(
            "title_english", sa.String(length=1000), nullable=True, comment="英文标题"
        ),
        sa.Column(
            "authors", sa.Text(), nullable=True, comment="作者 (JSON array string)"
        ),
        sa.Column(
            "journal", sa.String(length=500), nullable=True, comment="期刊/会议名"
        ),
        sa.Column("year", sa.Integer(), nullable=True, comment="发表年份"),
        sa.Column("doi", sa.String(length=500), nullable=True, comment="DOI"),
        sa.Column("volume", sa.String(length=50), nullable=True, comment="卷"),
        sa.Column("issue", sa.String(length=50), nullable=True, comment="期"),
        sa.Column("pages", sa.String(length=50), nullable=True, comment="页码"),
        sa.Column("abstract", sa.Text(), nullable=True, comment="摘要"),
        sa.Column("keywords", sa.Text(), nullable=True, comment="关键词 (逗号分隔)"),
        sa.Column(
            "language",
            sa.String(length=20),
            server_default="zh",
            nullable=False,
            comment="语言",
        ),
        sa.Column(
            "paper_type",
            sa.String(length=50),
            nullable=True,
            comment="类型: journal, thesis, conference, chapter, report",
        ),
        sa.Column(
            "source_url", sa.String(length=2000), nullable=True, comment="来源链接"
        ),
        sa.Column("full_text", sa.Text(), nullable=True, comment="全文文本"),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("doi"),
    )
    op.create_index(op.f("ix_papers_title"), "papers", ["title"], unique=False)
    op.create_table(
        "permissions",
        sa.Column(
            "resource", sa.String(length=100), nullable=False, comment="资源类型"
        ),
        sa.Column(
            "action",
            sa.String(length=100),
            nullable=False,
            comment="操作 (create, read, update, delete, export, publish, review, approve)",
        ),
        sa.Column("description", sa.Text(), nullable=True, comment="权限描述"),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "persons",
        sa.Column("name", sa.String(length=200), nullable=False, comment="姓名"),
        sa.Column(
            "name_pinyin", sa.String(length=200), nullable=True, comment="姓名拼音"
        ),
        sa.Column(
            "name_zh", sa.String(length=200), nullable=True, comment="中文名 (繁体)"
        ),
        sa.Column("courtesy_name", sa.String(length=200), nullable=True, comment="字"),
        sa.Column("pseudonym", sa.String(length=200), nullable=True, comment="号"),
        sa.Column("dynasty", sa.String(length=100), nullable=True, comment="朝代"),
        sa.Column(
            "birth_year", sa.Integer(), nullable=True, comment="出生年份 (负数=公元前)"
        ),
        sa.Column("death_year", sa.Integer(), nullable=True, comment="逝世年份"),
        sa.Column(
            "birth_place", sa.String(length=300), nullable=True, comment="出生地"
        ),
        sa.Column("biography", sa.Text(), nullable=True, comment="生平简介"),
        sa.Column(
            "biography_source",
            sa.String(length=500),
            nullable=True,
            comment="生平资料来源",
        ),
        sa.Column(
            "notable_works", sa.Text(), nullable=True, comment="代表著作 (逗号分隔)"
        ),
        sa.Column(
            "expertise", sa.String(length=500), nullable=True, comment="专长领域"
        ),
        sa.Column(
            "external_ref",
            sa.String(length=500),
            nullable=True,
            comment="外部参考 (Wikidata/百度百科)",
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "roles",
        sa.Column("name", sa.String(length=100), nullable=False, comment="角色名称"),
        sa.Column("description", sa.Text(), nullable=True, comment="角色描述"),
        sa.Column(
            "is_system",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="系统内置角色(不可删除)",
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("username", sa.String(length=100), nullable=False, comment="用户名"),
        sa.Column("email", sa.String(length=255), nullable=False, comment="邮箱"),
        sa.Column(
            "hashed_password",
            sa.String(length=255),
            nullable=False,
            comment="bcrypt 哈希密码",
        ),
        sa.Column(
            "display_name", sa.String(length=200), nullable=True, comment="显示名称"
        ),
        sa.Column(
            "affiliation", sa.String(length=500), nullable=True, comment="所属机构"
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="是否激活",
        ),
        sa.Column(
            "is_superuser",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="超级管理员",
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "books",
        sa.Column("title", sa.String(length=500), nullable=False, comment="书名"),
        sa.Column(
            "title_pinyin", sa.String(length=500), nullable=True, comment="书名拼音"
        ),
        sa.Column(
            "title_english", sa.String(length=500), nullable=True, comment="书名英文"
        ),
        sa.Column("author_id", sa.String(length=36), nullable=True, comment="作者 ID"),
        sa.Column("dynasty", sa.String(length=100), nullable=True, comment="成书朝代"),
        sa.Column("year", sa.Integer(), nullable=True, comment="成书年份"),
        sa.Column("category", sa.String(length=200), nullable=True, comment="分类"),
        sa.Column("abstract", sa.Text(), nullable=True, comment="内容摘要"),
        sa.Column(
            "language",
            sa.String(length=20),
            server_default="zh",
            nullable=False,
            comment="语言",
        ),
        sa.Column(
            "source_url", sa.String(length=2000), nullable=True, comment="来源链接"
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["persons.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_books_title"), "books", ["title"], unique=False)
    op.create_table(
        "documents",
        sa.Column("title", sa.String(length=500), nullable=False, comment="文献标题"),
        sa.Column(
            "title_pinyin", sa.String(length=500), nullable=True, comment="标题拼音"
        ),
        sa.Column(
            "title_english", sa.String(length=500), nullable=True, comment="标题英文"
        ),
        sa.Column(
            "author_id",
            sa.String(length=36),
            nullable=True,
            comment="关联作者 ID (Person)",
        ),
        sa.Column("dynasty", sa.String(length=100), nullable=True, comment="朝代"),
        sa.Column("year", sa.Integer(), nullable=True, comment="成书年份"),
        sa.Column(
            "category",
            sa.String(length=200),
            nullable=True,
            comment="分类 (针灸/本草/方剂/养生)",
        ),
        sa.Column("abstract", sa.Text(), nullable=True, comment="摘要"),
        sa.Column("content_text", sa.Text(), nullable=True, comment="全文文本"),
        sa.Column(
            "source_url", sa.String(length=2000), nullable=True, comment="来源链接"
        ),
        sa.Column("page_count", sa.Integer(), nullable=True, comment="页数"),
        sa.Column(
            "language",
            sa.String(length=20),
            server_default="zh",
            nullable=False,
            comment="语言",
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["persons.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "research_sessions",
        sa.Column(
            "user_id", sa.String(length=36), nullable=False, comment="所属用户 ID"
        ),
        sa.Column(
            "title",
            sa.String(length=500),
            server_default="未命名研究",
            nullable=False,
            comment="会话标题",
        ),
        sa.Column(
            "active_entities",
            sa.Text(),
            nullable=True,
            comment="当前打开的实体 ID 列表 (JSON)",
        ),
        sa.Column(
            "chat_history", sa.Text(), nullable=True, comment="AI 对话历史 (JSON)"
        ),
        sa.Column(
            "context_notes", sa.Text(), nullable=True, comment="研究笔记 (Markdown)"
        ),
        sa.Column(
            "workflow_state",
            sa.Text(),
            nullable=True,
            comment="当前研究流程快照 (JSON)",
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_research_sessions_user_id"),
        "research_sessions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "role_permission",
        sa.Column("role_id", sa.String(length=36), nullable=False),
        sa.Column("permission_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"], ["permissions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )
    op.create_table(
        "user_role",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )
    op.create_table(
        "chapters",
        sa.Column(
            "book_id", sa.String(length=36), nullable=False, comment="所属书籍 ID"
        ),
        sa.Column(
            "parent_id",
            sa.String(length=36),
            nullable=True,
            comment="父章节 ID (自引用层级)",
        ),
        sa.Column("title", sa.String(length=500), nullable=False, comment="章节标题"),
        sa.Column(
            "order", sa.Integer(), server_default="0", nullable=False, comment="排序"
        ),
        sa.Column(
            "description", sa.String(length=2000), nullable=True, comment="章节说明"
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(["book_id"], ["books.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_id"], ["chapters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chapters_book_id"), "chapters", ["book_id"], unique=False)
    op.create_table(
        "research_notes",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column(
            "entity_type", sa.String(length=50), nullable=True, comment="关联实体类型"
        ),
        sa.Column(
            "entity_id", sa.String(length=36), nullable=True, comment="关联实体 ID"
        ),
        sa.Column("content", sa.Text(), nullable=False, comment="笔记内容 (Markdown)"),
        sa.Column("tags", sa.String(length=500), nullable=True, comment="标签"),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"], ["research_sessions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_research_notes_session_id"),
        "research_notes",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "versions",
        sa.Column(
            "book_id", sa.String(length=36), nullable=False, comment="所属书籍 ID"
        ),
        sa.Column(
            "version_name", sa.String(length=300), nullable=False, comment="版本名称"
        ),
        sa.Column("era", sa.String(length=100), nullable=True, comment="朝代/时期"),
        sa.Column("year", sa.Integer(), nullable=True, comment="版本年份"),
        sa.Column(
            "repository", sa.String(length=500), nullable=True, comment="收藏机构"
        ),
        sa.Column("shelf_mark", sa.String(length=200), nullable=True, comment="索书号"),
        sa.Column(
            "editor", sa.String(length=200), nullable=True, comment="编者/校注者"
        ),
        sa.Column("description", sa.Text(), nullable=True, comment="版本描述"),
        sa.Column(
            "source_url", sa.String(length=2000), nullable=True, comment="来源链接"
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(["book_id"], ["books.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_versions_book_id"), "versions", ["book_id"], unique=False)
    op.create_table(
        "passages",
        sa.Column(
            "chapter_id", sa.String(length=36), nullable=False, comment="所属章节 ID"
        ),
        sa.Column(
            "version_id",
            sa.String(length=36),
            nullable=True,
            comment="所属版本 ID (版本特定文本)",
        ),
        sa.Column("content_text", sa.Text(), nullable=False, comment="条文正文"),
        sa.Column("translation", sa.Text(), nullable=True, comment="现代汉语翻译"),
        sa.Column("notes", sa.Text(), nullable=True, comment="注释"),
        sa.Column(
            "order", sa.Integer(), server_default="0", nullable=False, comment="排序"
        ),
        sa.Column(
            "tags", sa.String(length=1000), nullable=True, comment="标签 (逗号分隔)"
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(["chapter_id"], ["chapters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["version_id"], ["versions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_passages_chapter_id"), "passages", ["chapter_id"], unique=False
    )
    op.create_table(
        "version_diffs",
        sa.Column("source_version_id", sa.String(length=36), nullable=False),
        sa.Column("target_version_id", sa.String(length=36), nullable=False),
        sa.Column(
            "diff_data", sa.Text(), nullable=False, comment="JSON-encoded diff result"
        ),
        sa.Column("diff_summary", sa.Text(), nullable=True, comment="差异摘要"),
        sa.Column(
            "total_differences",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="差异总数",
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(
            ["source_version_id"], ["versions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["target_version_id"], ["versions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_version_diffs_source_version_id"),
        "version_diffs",
        ["source_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_version_diffs_target_version_id"),
        "version_diffs",
        ["target_version_id"],
        unique=False,
    )
    op.create_table(
        "version_relations",
        sa.Column(
            "source_version_id",
            sa.String(length=36),
            nullable=False,
            comment="源版本 ID",
        ),
        sa.Column(
            "target_version_id",
            sa.String(length=36),
            nullable=False,
            comment="目标版本 ID",
        ),
        sa.Column(
            "relation_type",
            sa.String(length=50),
            nullable=False,
            comment="关系类型: derived_from, revised_from, corrected_by, annotated_by, compared_with, referenced_by",
        ),
        sa.Column("description", sa.Text(), nullable=True, comment="关系说明"),
        sa.Column("evidence", sa.Text(), nullable=True, comment="关系依据/证据"),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(
            ["source_version_id"], ["versions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["target_version_id"], ["versions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_version_relations_source_version_id"),
        "version_relations",
        ["source_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_version_relations_target_version_id"),
        "version_relations",
        ["target_version_id"],
        unique=False,
    )
    op.create_table(
        "passage_mappings",
        sa.Column(
            "source_passage_id",
            sa.String(length=36),
            nullable=False,
            comment="源版本中的 Passage ID",
        ),
        sa.Column(
            "target_passage_id",
            sa.String(length=36),
            nullable=False,
            comment="目标版本中的 Passage ID",
        ),
        sa.Column(
            "mapping_type",
            sa.String(length=50),
            server_default="equivalent",
            nullable=False,
            comment="映射类型: equivalent(等同), variant(异文), missing(缺失), added(新增)",
        ),
        sa.Column("description", sa.Text(), nullable=True, comment="映射说明"),
        sa.Column(
            "is_verified",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="是否已校核",
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(
            ["source_passage_id"], ["passages.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["target_passage_id"], ["passages.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_passage_mappings_source_passage_id"),
        "passage_mappings",
        ["source_passage_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_passage_mappings_target_passage_id"),
        "passage_mappings",
        ["target_passage_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_passage_mappings_target_passage_id"), table_name="passage_mappings"
    )
    op.drop_index(
        op.f("ix_passage_mappings_source_passage_id"), table_name="passage_mappings"
    )
    op.drop_table("passage_mappings")
    op.drop_index(
        op.f("ix_version_relations_target_version_id"), table_name="version_relations"
    )
    op.drop_index(
        op.f("ix_version_relations_source_version_id"), table_name="version_relations"
    )
    op.drop_table("version_relations")
    op.drop_index(
        op.f("ix_version_diffs_target_version_id"), table_name="version_diffs"
    )
    op.drop_index(
        op.f("ix_version_diffs_source_version_id"), table_name="version_diffs"
    )
    op.drop_table("version_diffs")
    op.drop_index(op.f("ix_passages_chapter_id"), table_name="passages")
    op.drop_table("passages")
    op.drop_index(op.f("ix_versions_book_id"), table_name="versions")
    op.drop_table("versions")
    op.drop_index(op.f("ix_research_notes_session_id"), table_name="research_notes")
    op.drop_table("research_notes")
    op.drop_index(op.f("ix_chapters_book_id"), table_name="chapters")
    op.drop_table("chapters")
    op.drop_table("user_role")
    op.drop_table("role_permission")
    op.drop_index(op.f("ix_research_sessions_user_id"), table_name="research_sessions")
    op.drop_table("research_sessions")
    op.drop_table("documents")
    op.drop_index(op.f("ix_books_title"), table_name="books")
    op.drop_table("books")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("roles")
    op.drop_table("persons")
    op.drop_table("permissions")
    op.drop_index(op.f("ix_papers_title"), table_name="papers")
    op.drop_table("papers")
    op.drop_index(op.f("ix_images_related_entity_id"), table_name="images")
    op.drop_table("images")
    op.drop_index(
        op.f("ix_entity_relations_target_entity_type"), table_name="entity_relations"
    )
    op.drop_index(
        op.f("ix_entity_relations_target_entity_id"), table_name="entity_relations"
    )
    op.drop_index(
        op.f("ix_entity_relations_source_entity_type"), table_name="entity_relations"
    )
    op.drop_index(
        op.f("ix_entity_relations_source_entity_id"), table_name="entity_relations"
    )
    op.drop_table("entity_relations")
    # ### end Alembic commands ###
