"""add_query_history_and_citation_collection

Revision ID: 525e27e38f88
Revises: 9c710fa2d3f0
Create Date: 2026-07-02 14:02:55.776814
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '525e27e38f88'
down_revision: Union[str, None] = '9c710fa2d3f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citation_collections',
    sa.Column('session_id', sa.String(length=36), nullable=False, comment='所属研究会话 ID'),
    sa.Column('trace_json', sa.Text(), nullable=False, comment='完整 EvidenceTrace JSON，不可变'),
    sa.Column('citation_text', sa.Text(), nullable=False, comment='格式化引用文本'),
    sa.Column('source_document', sa.String(length=500), nullable=False, comment='来源文献名'),
    sa.Column('tags', sa.String(length=500), nullable=True, comment='用户标签'),
    sa.Column('notes', sa.Text(), nullable=True, comment='用户标注'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citation_collections_session_id'), 'citation_collections', ['session_id'], unique=False)
    op.create_table('query_histories',
    sa.Column('session_id', sa.String(length=36), nullable=False, comment='所属研究会话 ID'),
    sa.Column('query_text', sa.Text(), nullable=False, comment='查询原文'),
    sa.Column('query_type', sa.String(length=50), nullable=False, comment='查询类型: report / synthesis / research / education / graph / search'),
    sa.Column('result_summary', sa.Text(), nullable=True, comment='内部全保真追溯 JSON: {trace_id, document_id, chunk_id, passage_id, retrieval_score, retrieval_method, timestamp}'),
    sa.Column('citation_count', sa.Integer(), server_default='0', nullable=False, comment='返回的引用条数'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_histories_session_id'), 'query_histories', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_query_histories_session_id'), table_name='query_histories')
    op.drop_table('query_histories')
    op.drop_index(op.f('ix_citation_collections_session_id'), table_name='citation_collections')
    op.drop_table('citation_collections')
    # ### end Alembic commands ###
