"""add uploaded_by to documents

Revision ID: d30af4b7b824
Revises: d8e9f0a1b2c3
Create Date: 2026-07-23 02:23:39.461360
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = 'd30af4b7b824'
down_revision: Union[str, None] = 'd8e9f0a1b2c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'document_id',
               existing_type=sa.VARCHAR(length=36),
               comment='Parent document ID',
               existing_nullable=False)
    op.alter_column('document_chunks', 'chunk_index',
               existing_type=sa.INTEGER(),
               comment='Sequential index within the document (0-based)',
               existing_nullable=False)
    op.alter_column('document_chunks', 'content',
               existing_type=sa.TEXT(),
               comment='Chunk text content',
               existing_nullable=False)
    op.alter_column('document_chunks', 'token_count',
               existing_type=sa.INTEGER(),
               comment='Approximate character count (no tokenizer needed)',
               existing_nullable=True)
    op.alter_column('document_chunks', 'page_number',
               existing_type=sa.INTEGER(),
               comment='源文档页码 (1-based)',
               existing_nullable=True)
    op.alter_column('document_chunks', 'paragraph_index',
               existing_type=sa.INTEGER(),
               comment='源文档段落索引 (0-based)',
               existing_nullable=True)
    op.alter_column('document_chunks', 'ocr_confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='OCR 可信度 0.0-1.0，NULL 表示非 OCR 文本',
               existing_nullable=True)
    op.alter_column('document_chunks', 'evidence_weight',
               existing_type=sa.VARCHAR(length=20),
               comment='证据权重: primary | reference',
               existing_nullable=False,
               existing_server_default=sa.text("'primary'::character varying"))
    op.alter_column('document_chunks', 'citation_format',
               existing_type=sa.VARCHAR(length=200),
               comment='引文格式模板',
               existing_nullable=True)
    op.drop_index(op.f('idx_chunks_doc_page'), table_name='document_chunks')
    op.drop_constraint(op.f('uq_chunks_doc_index'), 'document_chunks', type_='unique')
    op.create_index('idx_chunks_doc_index', 'document_chunks', ['document_id', 'chunk_index'], unique=True)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_passage_id'), 'document_chunks', ['passage_id'], unique=False)
    op.add_column('documents', sa.Column('uploaded_by', sa.String(length=36), nullable=True, comment='上传者 user ID — NULL = 系统种子/公共文献'))
    op.alter_column('documents', 'raw_pdf_blob',
               existing_type=postgresql.BYTEA(),
               comment='原始 PDF 文件的二进制内容',
               existing_nullable=True)
    op.alter_column('documents', 'copyright_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               comment='版权状态: public_domain|open_access|licensed|user_uploaded_with_permission|unknown|metadata_only|forbidden_fulltext|commercial_restricted|pirated',
               existing_server_default=sa.text("'unknown'::character varying"))
    op.alter_column('documents', 'license_type',
               existing_type=sa.VARCHAR(length=100),
               comment='许可类型: CC-BY|CC-BY-NC|CC-BY-SA|CC0|custom',
               existing_nullable=True)
    op.alter_column('documents', 'authorization_basis',
               existing_type=sa.VARCHAR(length=200),
               comment='授权依据 (license URL / agreement ref / basis statement)',
               existing_nullable=True)
    op.alter_column('documents', 'review_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               comment='审核状态: pending_review|under_review|approved|rejected',
               existing_server_default=sa.text("'pending_review'::character varying"))
    op.alter_column('documents', 'reviewed_by',
               existing_type=sa.VARCHAR(length=36),
               comment='审核人 user ID',
               existing_nullable=True)
    op.alter_column('documents', 'reviewed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='审核时间',
               existing_nullable=True)
    op.alter_column('documents', 'rag_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment='是否允许进入 RAG (审核通过 + 版权允许后置为 true)',
               existing_server_default=sa.text('false'))
    op.alter_column('documents', 'content_checksum',
               existing_type=sa.VARCHAR(length=64),
               comment='全文 SHA-256 checksum',
               existing_nullable=True)
    op.alter_column('documents', 'source_name',
               existing_type=sa.VARCHAR(length=200),
               comment='摄入来源名称 (openalex/crossref/user_upload/等)',
               existing_nullable=True)
    op.alter_column('documents', 'withdrawn_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='撤回时间',
               existing_nullable=True)
    op.alter_column('documents', 'withdraw_reason',
               existing_type=sa.TEXT(),
               comment='撤回原因',
               existing_nullable=True)
    op.drop_index(op.f('idx_documents_session_id'), table_name='documents')
    op.create_index(op.f('ix_documents_session_id'), 'documents', ['session_id'], unique=False)
    op.create_index(op.f('ix_documents_uploaded_by'), 'documents', ['uploaded_by'], unique=False)
    op.create_foreign_key(None, 'documents', 'users', ['uploaded_by'], ['id'], ondelete='SET NULL')
    op.alter_column('entity_relations', 'source_entity_type',
               existing_type=sa.VARCHAR(length=50),
               comment='源实体类型',
               existing_comment='源实体类型: person, book, version, passage',
               existing_nullable=False)
    op.alter_column('entity_relations', 'target_entity_type',
               existing_type=sa.VARCHAR(length=50),
               comment='目标实体类型',
               existing_comment='目标实体类型: person, book, version, passage',
               existing_nullable=False)
    op.alter_column('entity_relations', 'relation_type',
               existing_type=sa.VARCHAR(length=50),
               comment='关系类型',
               existing_comment='关系类型: authored, compiled, commented_on, cited_in, studied, compared, referenced, related_to',
               existing_nullable=False)
    op.alter_column('entity_relations', 'evidence_level',
               existing_type=sa.INTEGER(),
               comment='证据等级 0-4: 0=无来源, 1=文献引用, 2=段落定位, 3=原文引证, 4=对勘证据',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('entity_relations', 'evidence',
               existing_type=sa.TEXT(),
               comment='[DEPRECATED] 自由文本证据 — 不再用于验证',
               existing_comment='关系依据/证据',
               existing_nullable=True)
    op.alter_column('entity_relations', 'evidence_version_id',
               existing_type=sa.VARCHAR(length=36),
               comment='证据来源 version ID',
               existing_nullable=True)
    op.alter_column('entity_relations', 'evidence_passage_id',
               existing_type=sa.VARCHAR(length=36),
               comment='证据来源 passage ID',
               existing_nullable=True)
    op.alter_column('entity_relations', 'evidence_source_uri',
               existing_type=sa.VARCHAR(length=500),
               comment='稳定来源 URI 或馆藏信息',
               existing_nullable=True)
    op.alter_column('entity_relations', 'evidence_status',
               existing_type=sa.VARCHAR(length=20),
               comment='证据状态: unverified, verified, rejected',
               existing_nullable=False,
               existing_server_default=sa.text("'unverified'::character varying"))
    op.alter_column('entity_relations', 'claim_text',
               existing_type=sa.TEXT(),
               comment='该关系所支持的具体学术论断',
               existing_nullable=True)
    op.alter_column('entity_relations', 'verified_by',
               existing_type=sa.VARCHAR(length=36),
               comment='校核人用户ID (FK to users)',
               existing_nullable=True)
    op.alter_column('entity_relations', 'verified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='校核时间',
               existing_nullable=True)
    op.drop_index(op.f('ix_entity_relations_active_dedup'), table_name='entity_relations', postgresql_where='(is_deleted = false)')
    op.create_index('ix_entity_relations_lookup', 'entity_relations', ['source_entity_type', 'source_entity_id', 'target_entity_type', 'target_entity_id', 'relation_type'], unique=False)
    op.alter_column('institutions', 'name',
               existing_type=sa.VARCHAR(length=300),
               comment='机构名称',
               existing_nullable=False)
    op.alter_column('institutions', 'type',
               existing_type=sa.VARCHAR(length=50),
               comment='类型: research / university / archive / institution',
               existing_nullable=False)
    op.alter_column('institutions', 'location',
               existing_type=sa.VARCHAR(length=300),
               comment='所在地',
               existing_nullable=True)
    op.alter_column('institutions', 'description',
               existing_type=sa.TEXT(),
               comment='机构简介',
               existing_nullable=True)
    op.alter_column('institutions', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='状态: draft / active / archived / deleted',
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.drop_index(op.f('idx_institutions_name'), table_name='institutions')
    op.drop_index(op.f('idx_institutions_type'), table_name='institutions')
    op.alter_column('tcm_entities', 'entity_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Entity type from canonical ontology',
               existing_nullable=False)
    op.alter_column('tcm_entities', 'name',
               existing_type=sa.VARCHAR(length=300),
               comment='Display name',
               existing_nullable=False)
    op.alter_column('tcm_entities', 'name_zh',
               existing_type=sa.VARCHAR(length=300),
               comment='Chinese name',
               existing_nullable=True)
    op.alter_column('tcm_entities', 'properties',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Type-specific properties as JSON',
               existing_nullable=True)
    op.alter_column('tcm_entities', 'description',
               existing_type=sa.TEXT(),
               comment='Description / biography / notes',
               existing_nullable=True)
    op.alter_column('tcm_entities', 'external_ref',
               existing_type=sa.VARCHAR(length=500),
               comment='External reference (Wikidata etc.)',
               existing_nullable=True)
    op.drop_index(op.f('ix_tcm_entities_type_name'), table_name='tcm_entities')
    op.alter_column('text_sentences', 'order',
               existing_type=sa.INTEGER(),
               comment='Sentence order within passage',
               existing_nullable=False)
    op.alter_column('text_sentences', 'text',
               existing_type=sa.TEXT(),
               comment='Sentence text',
               existing_nullable=False)
    op.alter_column('text_sentences', 'xml_id',
               existing_type=sa.VARCHAR(length=100),
               comment='TEI xml:id attribute',
               existing_nullable=True)
    op.drop_index(op.f('ix_text_sentences_passage_order'), table_name='text_sentences')
    op.alter_column('text_tokens', 'order',
               existing_type=sa.INTEGER(),
               comment='Token order within sentence',
               existing_nullable=False)
    op.alter_column('text_tokens', 'text',
               existing_type=sa.VARCHAR(length=50),
               comment='Token surface form',
               existing_nullable=False)
    op.alter_column('text_tokens', 'lemma',
               existing_type=sa.VARCHAR(length=50),
               comment='Lemma/base form',
               existing_nullable=True)
    op.alter_column('text_tokens', 'pos',
               existing_type=sa.VARCHAR(length=20),
               comment='Part of speech tag',
               existing_nullable=True)
    op.alter_column('text_tokens', 'start_offset',
               existing_type=sa.INTEGER(),
               comment='Character offset start in sentence',
               existing_nullable=True)
    op.alter_column('text_tokens', 'end_offset',
               existing_type=sa.INTEGER(),
               comment='Character offset end in sentence',
               existing_nullable=True)
    op.drop_index(op.f('ix_text_tokens_sentence_order'), table_name='text_tokens')
    op.alter_column('textual_variants', 'source_version_id',
               existing_type=sa.VARCHAR(length=36),
               comment='源版本 ID',
               existing_nullable=False)
    op.alter_column('textual_variants', 'target_version_id',
               existing_type=sa.VARCHAR(length=36),
               comment='目标版本 ID',
               existing_nullable=False)
    op.alter_column('textual_variants', 'source_passage_id',
               existing_type=sa.VARCHAR(length=36),
               comment='源段落 ID',
               existing_nullable=True)
    op.alter_column('textual_variants', 'target_passage_id',
               existing_type=sa.VARCHAR(length=36),
               comment='目标段落 ID',
               existing_nullable=True)
    op.alter_column('textual_variants', 'source_sentence_id',
               existing_type=sa.VARCHAR(length=36),
               comment='源句子 ID',
               existing_nullable=True)
    op.alter_column('textual_variants', 'target_sentence_id',
               existing_type=sa.VARCHAR(length=36),
               comment='目标句子 ID',
               existing_nullable=True)
    op.alter_column('textual_variants', 'location',
               existing_type=sa.VARCHAR(length=200),
               comment='异文位置描述',
               existing_nullable=True)
    op.alter_column('textual_variants', 'lemma',
               existing_type=sa.VARCHAR(length=200),
               comment='词条/引理',
               existing_nullable=True)
    op.alter_column('textual_variants', 'reading',
               existing_type=sa.TEXT(),
               comment='异文内容',
               existing_nullable=False)
    op.alter_column('textual_variants', 'variant_type',
               existing_type=sa.VARCHAR(length=50),
               comment='异文类型: substitution, addition, deletion, transposition',
               existing_nullable=True)
    op.alter_column('textual_variants', 'apparatus',
               existing_type=sa.TEXT(),
               comment='校勘记原文',
               existing_nullable=True)
    op.alter_column('textual_variants', 'verification_status',
               existing_type=sa.VARCHAR(length=20),
               comment='校核状态: unverified, verified, rejected',
               existing_nullable=False,
               existing_server_default=sa.text("'unverified'::character varying"))
    op.drop_index(op.f('ix_textual_variants_versions'), table_name='textual_variants')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_textual_variants_versions'), 'textual_variants', ['source_version_id', 'target_version_id'], unique=False)
    op.alter_column('textual_variants', 'verification_status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='校核状态: unverified, verified, rejected',
               existing_nullable=False,
               existing_server_default=sa.text("'unverified'::character varying"))
    op.alter_column('textual_variants', 'apparatus',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='校勘记原文',
               existing_nullable=True)
    op.alter_column('textual_variants', 'variant_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='异文类型: substitution, addition, deletion, transposition',
               existing_nullable=True)
    op.alter_column('textual_variants', 'reading',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='异文内容',
               existing_nullable=False)
    op.alter_column('textual_variants', 'lemma',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='词条/引理',
               existing_nullable=True)
    op.alter_column('textual_variants', 'location',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='异文位置描述',
               existing_nullable=True)
    op.alter_column('textual_variants', 'target_sentence_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='目标句子 ID',
               existing_nullable=True)
    op.alter_column('textual_variants', 'source_sentence_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='源句子 ID',
               existing_nullable=True)
    op.alter_column('textual_variants', 'target_passage_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='目标段落 ID',
               existing_nullable=True)
    op.alter_column('textual_variants', 'source_passage_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='源段落 ID',
               existing_nullable=True)
    op.alter_column('textual_variants', 'target_version_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='目标版本 ID',
               existing_nullable=False)
    op.alter_column('textual_variants', 'source_version_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='源版本 ID',
               existing_nullable=False)
    op.create_index(op.f('ix_text_tokens_sentence_order'), 'text_tokens', ['sentence_id', 'order'], unique=False)
    op.alter_column('text_tokens', 'end_offset',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Character offset end in sentence',
               existing_nullable=True)
    op.alter_column('text_tokens', 'start_offset',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Character offset start in sentence',
               existing_nullable=True)
    op.alter_column('text_tokens', 'pos',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Part of speech tag',
               existing_nullable=True)
    op.alter_column('text_tokens', 'lemma',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Lemma/base form',
               existing_nullable=True)
    op.alter_column('text_tokens', 'text',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Token surface form',
               existing_nullable=False)
    op.alter_column('text_tokens', 'order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Token order within sentence',
               existing_nullable=False)
    op.create_index(op.f('ix_text_sentences_passage_order'), 'text_sentences', ['passage_id', 'order'], unique=False)
    op.alter_column('text_sentences', 'xml_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='TEI xml:id attribute',
               existing_nullable=True)
    op.alter_column('text_sentences', 'text',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Sentence text',
               existing_nullable=False)
    op.alter_column('text_sentences', 'order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Sentence order within passage',
               existing_nullable=False)
    op.create_index(op.f('ix_tcm_entities_type_name'), 'tcm_entities', ['entity_type', 'name'], unique=False)
    op.alter_column('tcm_entities', 'external_ref',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='External reference (Wikidata etc.)',
               existing_nullable=True)
    op.alter_column('tcm_entities', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Description / biography / notes',
               existing_nullable=True)
    op.alter_column('tcm_entities', 'properties',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Type-specific properties as JSON',
               existing_nullable=True)
    op.alter_column('tcm_entities', 'name_zh',
               existing_type=sa.VARCHAR(length=300),
               comment=None,
               existing_comment='Chinese name',
               existing_nullable=True)
    op.alter_column('tcm_entities', 'name',
               existing_type=sa.VARCHAR(length=300),
               comment=None,
               existing_comment='Display name',
               existing_nullable=False)
    op.alter_column('tcm_entities', 'entity_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Entity type from canonical ontology',
               existing_nullable=False)
    op.create_index(op.f('idx_institutions_type'), 'institutions', ['type'], unique=False)
    op.create_index(op.f('idx_institutions_name'), 'institutions', ['name'], unique=False)
    op.alter_column('institutions', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='状态: draft / active / archived / deleted',
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('institutions', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='机构简介',
               existing_nullable=True)
    op.alter_column('institutions', 'location',
               existing_type=sa.VARCHAR(length=300),
               comment=None,
               existing_comment='所在地',
               existing_nullable=True)
    op.alter_column('institutions', 'type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='类型: research / university / archive / institution',
               existing_nullable=False)
    op.alter_column('institutions', 'name',
               existing_type=sa.VARCHAR(length=300),
               comment=None,
               existing_comment='机构名称',
               existing_nullable=False)
    op.drop_index('ix_entity_relations_lookup', table_name='entity_relations')
    op.create_index(op.f('ix_entity_relations_active_dedup'), 'entity_relations', ['source_entity_type', 'source_entity_id', 'target_entity_type', 'target_entity_id', 'relation_type'], unique=True, postgresql_where='(is_deleted = false)')
    op.alter_column('entity_relations', 'verified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='校核时间',
               existing_nullable=True)
    op.alter_column('entity_relations', 'verified_by',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='校核人用户ID (FK to users)',
               existing_nullable=True)
    op.alter_column('entity_relations', 'claim_text',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='该关系所支持的具体学术论断',
               existing_nullable=True)
    op.alter_column('entity_relations', 'evidence_status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='证据状态: unverified, verified, rejected',
               existing_nullable=False,
               existing_server_default=sa.text("'unverified'::character varying"))
    op.alter_column('entity_relations', 'evidence_source_uri',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='稳定来源 URI 或馆藏信息',
               existing_nullable=True)
    op.alter_column('entity_relations', 'evidence_passage_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='证据来源 passage ID',
               existing_nullable=True)
    op.alter_column('entity_relations', 'evidence_version_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='证据来源 version ID',
               existing_nullable=True)
    op.alter_column('entity_relations', 'evidence',
               existing_type=sa.TEXT(),
               comment='关系依据/证据',
               existing_comment='[DEPRECATED] 自由文本证据 — 不再用于验证',
               existing_nullable=True)
    op.alter_column('entity_relations', 'evidence_level',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='证据等级 0-4: 0=无来源, 1=文献引用, 2=段落定位, 3=原文引证, 4=对勘证据',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('entity_relations', 'relation_type',
               existing_type=sa.VARCHAR(length=50),
               comment='关系类型: authored, compiled, commented_on, cited_in, studied, compared, referenced, related_to',
               existing_comment='关系类型',
               existing_nullable=False)
    op.alter_column('entity_relations', 'target_entity_type',
               existing_type=sa.VARCHAR(length=50),
               comment='目标实体类型: person, book, version, passage',
               existing_comment='目标实体类型',
               existing_nullable=False)
    op.alter_column('entity_relations', 'source_entity_type',
               existing_type=sa.VARCHAR(length=50),
               comment='源实体类型: person, book, version, passage',
               existing_comment='源实体类型',
               existing_nullable=False)
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_uploaded_by'), table_name='documents')
    op.drop_index(op.f('ix_documents_session_id'), table_name='documents')
    op.create_index(op.f('idx_documents_session_id'), 'documents', ['session_id'], unique=False)
    op.alter_column('documents', 'withdraw_reason',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='撤回原因',
               existing_nullable=True)
    op.alter_column('documents', 'withdrawn_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='撤回时间',
               existing_nullable=True)
    op.alter_column('documents', 'source_name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='摄入来源名称 (openalex/crossref/user_upload/等)',
               existing_nullable=True)
    op.alter_column('documents', 'content_checksum',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='全文 SHA-256 checksum',
               existing_nullable=True)
    op.alter_column('documents', 'rag_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment=None,
               existing_comment='是否允许进入 RAG (审核通过 + 版权允许后置为 true)',
               existing_server_default=sa.text('false'))
    op.alter_column('documents', 'reviewed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='审核时间',
               existing_nullable=True)
    op.alter_column('documents', 'reviewed_by',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='审核人 user ID',
               existing_nullable=True)
    op.alter_column('documents', 'review_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               comment=None,
               existing_comment='审核状态: pending_review|under_review|approved|rejected',
               existing_server_default=sa.text("'pending_review'::character varying"))
    op.alter_column('documents', 'authorization_basis',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='授权依据 (license URL / agreement ref / basis statement)',
               existing_nullable=True)
    op.alter_column('documents', 'license_type',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='许可类型: CC-BY|CC-BY-NC|CC-BY-SA|CC0|custom',
               existing_nullable=True)
    op.alter_column('documents', 'copyright_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               comment=None,
               existing_comment='版权状态: public_domain|open_access|licensed|user_uploaded_with_permission|unknown|metadata_only|forbidden_fulltext|commercial_restricted|pirated',
               existing_server_default=sa.text("'unknown'::character varying"))
    op.alter_column('documents', 'raw_pdf_blob',
               existing_type=postgresql.BYTEA(),
               comment=None,
               existing_comment='原始 PDF 文件的二进制内容',
               existing_nullable=True)
    op.drop_column('documents', 'uploaded_by')
    op.drop_index(op.f('ix_document_chunks_passage_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index('idx_chunks_doc_index', table_name='document_chunks')
    op.create_unique_constraint(op.f('uq_chunks_doc_index'), 'document_chunks', ['document_id', 'chunk_index'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_chunks_doc_page'), 'document_chunks', ['document_id', 'page_number'], unique=False)
    op.alter_column('document_chunks', 'citation_format',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='引文格式模板',
               existing_nullable=True)
    op.alter_column('document_chunks', 'evidence_weight',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='证据权重: primary | reference',
               existing_nullable=False,
               existing_server_default=sa.text("'primary'::character varying"))
    op.alter_column('document_chunks', 'ocr_confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='OCR 可信度 0.0-1.0，NULL 表示非 OCR 文本',
               existing_nullable=True)
    op.alter_column('document_chunks', 'paragraph_index',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='源文档段落索引 (0-based)',
               existing_nullable=True)
    op.alter_column('document_chunks', 'page_number',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='源文档页码 (1-based)',
               existing_nullable=True)
    op.alter_column('document_chunks', 'token_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Approximate character count (no tokenizer needed)',
               existing_nullable=True)
    op.alter_column('document_chunks', 'content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Chunk text content',
               existing_nullable=False)
    op.alter_column('document_chunks', 'chunk_index',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Sequential index within the document (0-based)',
               existing_nullable=False)
    op.alter_column('document_chunks', 'document_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='Parent document ID',
               existing_nullable=False)
    # ### end Alembic commands ###
