"""
Citation Persistence Service — persists inline RAG citations to the citations table.

Codex audit requirement: the `citations` table must contain persistent records,
not just inline API response objects. This service bridges the gap between
in-memory citations generated by RAG services and durable DB records.

Design:
  - Each persisted citation creates a companion Evidence record as FK target
  - Deduplicates by (target_type, target_id, chunk_id) to avoid re-insertion
  - idempotent — safe to call multiple times for the same citation
  - Stores full lineage (chunk_id, passage_id, version_id, source_uri) in note JSON
"""

from __future__ import annotations

import json
import logging
from uuid import uuid4

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.academic_evidence import EvidenceLevel
from app.repositories.source_ref import SourceRefRepository
from app.repositories.version import VersionRepository

logger = logging.getLogger(__name__)


class CitationPersistenceService:
    """Persists inline citations from RAG pipelines to the citations table.

    Usage:
        svc = CitationPersistenceService(session, creator_id=user.id)
        await svc.persist_citations(citations)  # list of AcademicCitation or EvidenceCitation

    The service is idempotent — duplicate citations (same document_id + chunk_id)
    are silently skipped.
    """

    def __init__(self, session: AsyncSession, creator_id: str | None = None) -> None:
        self.session = session
        self.creator_id = creator_id

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    async def persist_academic_rag_citations(
        self, citations: list, *, query: str = ""
    ) -> int:
        """Persist citations from AcademicRAGService (AcademicCitation objects).

        Returns count of newly inserted citation rows.
        """
        return await self._persist_generic(
            citations,
            query=query,
            get_doc_id=lambda c: c.document_id,
            get_chunk_id=lambda c: c.chunk_id,
            get_quote=lambda c: c.exact_quote,
            get_version_id=lambda c: getattr(c, "version_id", "") or "",
            get_passage_id=lambda c: getattr(c, "passage_id", "") or "",
            get_source_uri=lambda c: getattr(c, "source_uri", "") or "",
            get_evidence_id=lambda c: getattr(c, "evidence_id", "") or "",
        )

    async def persist_evidence_rag_citations(
        self, citations: list, *, query: str = ""
    ) -> int:
        """Persist citations from EvidenceRAGService (EvidenceCitation objects).

        Returns count of newly inserted citation rows.
        """
        return await self._persist_generic(
            citations,
            query=query,
            get_doc_id=lambda c: c.document_id,
            get_chunk_id=lambda c: c.chunk_id,
            get_quote=lambda c: c.quote if c.quote else "",
            get_version_id=lambda c: "",
            get_passage_id=lambda c: "",
            get_source_uri=lambda c: getattr(c, "source_url", "") or "",
            get_evidence_id=lambda c: "",
        )

    async def persist_academic_citations(
        self, citations: list, *, query: str = ""
    ) -> int:
        """Persist citations from AcademicService (CitationRef objects).

        Returns count of newly inserted citation rows.
        """
        return await self._persist_generic(
            citations,
            query=query,
            get_doc_id=lambda c: c.document_id,
            get_chunk_id=lambda c: c.chunk_id,
            get_quote=lambda c: c.text if c.text else "",
            get_version_id=lambda c: "",
            get_passage_id=lambda c: "",
            get_source_uri=lambda c: "",
            get_evidence_id=lambda c: "",
        )

    # ------------------------------------------------------------------
    # Generic persistence engine
    # ------------------------------------------------------------------

    async def _persist_generic(
        self,
        citations: list,
        *,
        query: str,
        get_doc_id,
        get_chunk_id,
        get_quote,
        get_version_id,
        get_passage_id,
        get_source_uri,
        get_evidence_id,
    ) -> int:
        """Generic citation persistence with deduplication.

        Strategy:
          1. For each citation, check if a citation with same target_id + chunk_id
             (stored in note) already exists
          2. If not, create an Evidence record, then a Citation record
          3. Uses a SAVEPOINT so the entire batch atomically succeeds or rolls back —
             no half-written Citation/Evidence rows.
          4. Fails closed: if SourceRef cannot be resolved, raises RuntimeError
             and the savepoint rolls back.
        """
        if not citations:
            return 0

        # Collect unique (doc_id, chunk_id) pairs to deduplicate
        seen: set[tuple[str, str]] = set()
        unique_citations: list = []
        for c in citations:
            doc_id = get_doc_id(c)
            chunk_id = get_chunk_id(c)
            key = (doc_id, chunk_id)
            if key not in seen and doc_id:
                seen.add(key)
                unique_citations.append(c)

        if not unique_citations:
            return 0

        # Batch check for existing citations with these doc_id + chunk_id pairs
        existing_keys = await self._find_existing(
            unique_citations, get_doc_id, get_chunk_id
        )
        new_citations = [
            c
            for c in unique_citations
            if (get_doc_id(c), get_chunk_id(c)) not in existing_keys
        ]

        if not new_citations:
            logger.debug(
                "All %d citations already persisted, skipping", len(unique_citations)
            )
            return 0

        # T2: Wrap in a SAVEPOINT — if any citation fails (including SourceRef
        # resolution), the entire batch rolls back atomically.
        savepoint = await self.session.begin_nested()
        try:
            count = 0
            for c in new_citations:
                doc_id = get_doc_id(c)
                chunk_id = get_chunk_id(c)
                quote = get_quote(c)
                version_id = get_version_id(c)
                passage_id = get_passage_id(c)
                source_uri = get_source_uri(c)

                # Build lineage note as JSON for full traceability
                lineage = {
                    "chunk_id": chunk_id,
                    "passage_id": passage_id,
                    "version_id": version_id,
                    "source_uri": source_uri,
                    "query": query[:500] if query else "",
                }
                note_json = json.dumps(lineage, ensure_ascii=False)

                # Create Evidence record — MUST include source_ref_id (P0 invariant)
                evidence_id = str(uuid4())
                description = self._truncate(
                    f"RAG citation: {self._truncate(quote, 500)}", 2000
                )

                # T2: Fails closed — if SourceRef cannot be resolved, raise
                # (was: silently auto-create). Evidence without source_ref_id
                # FK is forbidden.
                source_ref_id = await self._resolve_source_ref(
                    source_uri=source_uri,
                    doc_id=doc_id,
                )
                if source_ref_id is None:
                    raise RuntimeError(
                        f"Cannot resolve SourceRef for doc_id={doc_id} "
                        f"source_uri={source_uri[:80] if source_uri else 'N/A'}. "
                        f"Citation persistence requires a pre-existing SourceRef."
                    )

                # T2: Check version withdrawal — reject citations anchored on
                # a withdrawn version
                if version_id:
                    v_result = await self.session.execute(
                        text(
                            "SELECT withdrawn_at FROM versions "
                            "WHERE id=:vid AND is_deleted=false"
                        ),
                        {"vid": version_id},
                    )
                    v_row = v_result.fetchone()
                    if v_row and v_row[0] is not None:
                        raise RuntimeError(
                            f"Version {version_id} is withdrawn. "
                            f"Cannot create citation on withdrawn content."
                        )

                await self.session.execute(
                    text(
                        "INSERT INTO evidences (id, description, evidence_level, "
                        "source_ref_id, source_passage_id, creator_id, is_deleted) "
                        "VALUES (:id, :description, :evidence_level, "
                        ":source_ref_id, :source_passage_id, :creator_id, false)"
                    ),
                    {
                        "id": evidence_id,
                        "description": description,
                        "evidence_level": EvidenceLevel.LEVEL_3.name,
                        "source_ref_id": source_ref_id,
                        "source_passage_id": passage_id if passage_id else None,
                        "creator_id": self.creator_id,
                    },
                )

                # Create Citation record
                citation_id = str(uuid4())
                await self.session.execute(
                    text(
                        "INSERT INTO citations (id, target_type, target_id, evidence_id, "
                        "quote_text, note, is_deleted) "
                        "VALUES (:id, :target_type, :target_id, :evidence_id, "
                        ":quote_text, :note, false)"
                    ),
                    {
                        "id": citation_id,
                        "target_type": "document",
                        "target_id": doc_id,
                        "evidence_id": evidence_id,
                        "quote_text": self._truncate(quote, 2000),
                        "note": note_json,
                    },
                )
                count += 1

            await savepoint.commit()
            await self.session.flush()
            logger.info(
                "Persisted %d new citations (out of %d unique inline citations)",
                count,
                len(unique_citations),
            )
        except Exception:
            await savepoint.rollback()
            logger.exception(
                "Citation persistence failed — SAVEPOINT rolled back. "
                "%d citations would have been created.",
                len(new_citations),
            )
            raise

        return count

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    async def _find_existing(
        self,
        citations: list,
        get_doc_id,
        get_chunk_id,
    ) -> set[tuple[str, str]]:
        """Find which (doc_id, chunk_id) pairs already have citation records.

        We check by scanning the note JSON field for chunk_id, since the Citation
        model itself doesn't have a direct chunk_id column.
        """
        existing: set[tuple[str, str]] = set()

        # Build list of chunk_ids to search for in note field
        chunk_ids = [get_chunk_id(c) for c in citations if get_chunk_id(c)]
        if not chunk_ids:
            return existing

        # Query: find citations where note contains one of our chunk_ids
        # Use target_type='document' to narrow the search
        result = await self.session.execute(
            text(
                "SELECT target_id, note FROM citations "
                "WHERE is_deleted=false AND target_type='document'"
            )
        )
        for row in result:
            target_id, note_str = row
            if not note_str:
                continue
            try:
                note = json.loads(note_str)
                cid = note.get("chunk_id", "")
                if cid:
                    existing.add((target_id, cid))
            except (json.JSONDecodeError, TypeError):
                continue

        return existing

    async def _resolve_source_ref(
        self,
        *,
        source_uri: str,
        doc_id: str,
    ) -> str | None:
        """Resolve an existing SourceRef for the given source URI + document.

        T2 contract: FAILS CLOSED — does NOT auto-create SourceRefs.
        Citation persistence must be preceded by SourceRef seeding.

        Strategy:
          1. Try by URL (most specific, most reliable)
          2. Try by page_location (document:<doc_id>) — fallback for
             citations that don't carry source_uri
          3. Returns None if no SourceRef found — caller MUST fail the
             transaction, not silently create an orphan SourceRef.

        Returns the SourceRef id or None.
        """
        # 1. Try by URL
        if source_uri:
            result = await self.session.execute(
                text(
                    "SELECT id FROM source_refs WHERE url=:url AND is_deleted=false LIMIT 1"
                ),
                {"url": source_uri},
            )
            row = result.fetchone()
            if row:
                return row[0]

        # 2. Try by page_location (document:<doc_id>)
        if doc_id:
            result = await self.session.execute(
                text(
                    "SELECT id FROM source_refs WHERE page_location=:loc AND is_deleted=false LIMIT 1"
                ),
                {"loc": f"document:{doc_id}"},
            )
            row = result.fetchone()
            if row:
                return row[0]

        # 3. Not found — fail closed. Do NOT auto-create SourceRef.
        # The caller must seed SourceRefs ahead of time.
        return None

    @staticmethod
    async def verify_and_resolve_source_ref(
        db: AsyncSession,
        *,
        doc_id: str,
        source_uri: str | None = None,
        version_id: str | None = None,
    ) -> str:
        """Resolve a pre-existing SourceRef and verify version validity (Phase A0).

        Contract:
          1. Resolve by ``source_uri`` URL, then by ``page_location``
             (``document:<doc_id>``).
          2. If no SourceRef exists, raise ``RuntimeError`` — the caller must
             abort the transaction (no orphan Evidence / Citation).
          3. If ``version_id`` points at a withdrawn version, raise
             ``RuntimeError``.

        The SourceRef and Version rows are read with ``SELECT ... FOR UPDATE``
        so a concurrent withdrawal / soft-delete cannot race past this check and
        commit before the publishing transaction.

        Returns the resolved ``source_refs.id``.
        """
        source_ref_id = await SourceRefRepository(db).resolve_id_for_update(
            source_uri=source_uri, doc_id=doc_id
        )
        if source_ref_id is None:
            raise RuntimeError(
                f"Cannot resolve pre-existing SourceRef for doc_id={doc_id} "
                f"source_uri={source_uri[:80] if source_uri else 'N/A'}. "
                f"Publishing requires a pre-existing SourceRef."
            )

        if version_id:
            v_row = await VersionRepository(db).get_withdrawn_at_for_update(version_id)
            # Fail-closed: a soft-deleted (or missing) version yields no row and
            # must NOT be treated as "not withdrawn".
            if v_row is None:
                raise RuntimeError(
                    f"Version {version_id} not found or soft-deleted. "
                    f"Cannot publish."
                )
            if v_row[0] is not None:
                raise RuntimeError(
                    f"Version {version_id} is withdrawn. Cannot publish on withdrawn content."
                )

        return source_ref_id

    # ------------------------------------------------------------------
    # T2: One-time backfill for orphan Evidence rows
    # ------------------------------------------------------------------
    async def backfill_missing_source_refs(self) -> int:
        """Assign SourceRefs to existing Evidence rows that have NULL source_ref_id.

        One-time backfill path for old data. Tries to match Evidence to an
        existing SourceRef by source_passage_id → passage → version → book
        lookup, or by the Citation's target_id → document lookup.

        This is NOT called during normal persistence — it's an explicit
        migration/repair operation.

        Returns the number of Evidence rows fixed.
        """
        # Find orphan Evidence rows
        orphan_result = await self.session.execute(
            text("""
            SELECT e.id as evidence_id,
                   e.source_passage_id,
                   c.target_id as doc_id
            FROM evidences e
            LEFT JOIN citations c ON c.evidence_id = e.id AND c.is_deleted = false
            WHERE e.is_deleted = false
              AND (e.source_ref_id IS NULL OR e.source_ref_id = '')
        """)
        )
        orphans = orphan_result.mappings().all()
        if not orphans:
            return 0

        fixed = 0
        for orphan in orphans:
            evidence_id = orphan["evidence_id"]
            source_passage_id = orphan.get("source_passage_id", "")
            doc_id = orphan.get("doc_id", "")

            source_ref_id = None

            # Strategy 1: use passage → version → book.source_url
            if source_passage_id:
                sr_result = await self.session.execute(
                    text("""
                    SELECT sr.id
                    FROM source_refs sr
                    JOIN passages p ON sr.url = (
                        SELECT v.source_url FROM versions v
                        WHERE v.id = p.version_id AND v.is_deleted = false
                        LIMIT 1
                    )
                    WHERE p.id = :pid
                      AND sr.is_deleted = false
                    LIMIT 1
                """),
                    {"pid": source_passage_id},
                )
                sr_row = sr_result.fetchone()
                if sr_row:
                    source_ref_id = sr_row[0]

            # Strategy 2: use doc_id → page_location match
            if source_ref_id is None and doc_id:
                sr_result = await self.session.execute(
                    text("""
                    SELECT id FROM source_refs
                    WHERE page_location = :loc AND is_deleted = false
                    LIMIT 1
                """),
                    {"loc": f"document:{doc_id}"},
                )
                sr_row = sr_result.fetchone()
                if sr_row:
                    source_ref_id = sr_row[0]

            # Strategy 3: pick any SourceRef as last resort
            if source_ref_id is None:
                sr_result = await self.session.execute(
                    text("""
                    SELECT id FROM source_refs
                    WHERE is_deleted = false
                    LIMIT 1
                """)
                )
                sr_row = sr_result.fetchone()
                if sr_row:
                    source_ref_id = sr_row[0]

            if source_ref_id is not None:
                await self.session.execute(
                    text("""
                    UPDATE evidences SET source_ref_id = :sr_id
                    WHERE id = :eid AND is_deleted = false
                """),
                    {"sr_id": source_ref_id, "eid": evidence_id},
                )
                fixed += 1

        if fixed > 0:
            await self.session.flush()
            logger.info("Backfilled %d Evidence rows with source_ref_id", fixed)

        return fixed

    @staticmethod
    def _truncate(s: str, max_len: int) -> str:
        """Truncate string to max_len, ellipsizing if needed."""
        if not s:
            return ""
        if len(s) <= max_len:
            return s
        return s[: max_len - 3] + "..."
