"""
Citation Persistence Service — persists inline RAG citations to the citations table.

Codex audit requirement: the `citations` table must contain persistent records,
not just inline API response objects. This service bridges the gap between
in-memory citations generated by RAG services and durable DB records.

Design:
  - Each persisted citation creates a companion Evidence record as FK target
  - Deduplicates by (target_type, target_id, chunk_id) to avoid re-insertion
  - idempotent — safe to call multiple times for the same citation
  - Stores full lineage (chunk_id, passage_id, version_id, source_uri) in note JSON
"""

from __future__ import annotations

import json
import logging
from uuid import uuid4

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.academic_evidence import EvidenceLevel

logger = logging.getLogger(__name__)


class CitationPersistenceService:
    """Persists inline citations from RAG pipelines to the citations table.

    Usage:
        svc = CitationPersistenceService(session, creator_id=user.id)
        await svc.persist_citations(citations)  # list of AcademicCitation or EvidenceCitation

    The service is idempotent — duplicate citations (same document_id + chunk_id)
    are silently skipped.
    """

    def __init__(self, session: AsyncSession, creator_id: str | None = None) -> None:
        self.session = session
        self.creator_id = creator_id

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    async def persist_academic_rag_citations(
        self, citations: list, *, query: str = ""
    ) -> int:
        """Persist citations from AcademicRAGService (AcademicCitation objects).

        Returns count of newly inserted citation rows.
        """
        return await self._persist_generic(
            citations,
            query=query,
            get_doc_id=lambda c: c.document_id,
            get_chunk_id=lambda c: c.chunk_id,
            get_quote=lambda c: c.exact_quote,
            get_version_id=lambda c: getattr(c, "version_id", "") or "",
            get_passage_id=lambda c: getattr(c, "passage_id", "") or "",
            get_source_uri=lambda c: getattr(c, "source_uri", "") or "",
            get_evidence_id=lambda c: getattr(c, "evidence_id", "") or "",
        )

    async def persist_evidence_rag_citations(
        self, citations: list, *, query: str = ""
    ) -> int:
        """Persist citations from EvidenceRAGService (EvidenceCitation objects).

        Returns count of newly inserted citation rows.
        """
        return await self._persist_generic(
            citations,
            query=query,
            get_doc_id=lambda c: c.document_id,
            get_chunk_id=lambda c: c.chunk_id,
            get_quote=lambda c: c.quote if c.quote else "",
            get_version_id=lambda c: "",
            get_passage_id=lambda c: "",
            get_source_uri=lambda c: getattr(c, "source_url", "") or "",
            get_evidence_id=lambda c: "",
        )

    async def persist_academic_citations(
        self, citations: list, *, query: str = ""
    ) -> int:
        """Persist citations from AcademicService (CitationRef objects).

        Returns count of newly inserted citation rows.
        """
        return await self._persist_generic(
            citations,
            query=query,
            get_doc_id=lambda c: c.document_id,
            get_chunk_id=lambda c: c.chunk_id,
            get_quote=lambda c: c.text if c.text else "",
            get_version_id=lambda c: "",
            get_passage_id=lambda c: "",
            get_source_uri=lambda c: "",
            get_evidence_id=lambda c: "",
        )

    # ------------------------------------------------------------------
    # Generic persistence engine
    # ------------------------------------------------------------------

    async def _persist_generic(
        self,
        citations: list,
        *,
        query: str,
        get_doc_id,
        get_chunk_id,
        get_quote,
        get_version_id,
        get_passage_id,
        get_source_uri,
        get_evidence_id,
    ) -> int:
        """Generic citation persistence with deduplication.

        Strategy:
          1. For each citation, check if a citation with same target_id + chunk_id
             (stored in note) already exists
          2. If not, create an Evidence record, then a Citation record
          3. Batch-commit all new records
        """
        if not citations:
            return 0

        # Collect unique (doc_id, chunk_id) pairs to deduplicate
        seen: set[tuple[str, str]] = set()
        unique_citations: list = []
        for c in citations:
            doc_id = get_doc_id(c)
            chunk_id = get_chunk_id(c)
            key = (doc_id, chunk_id)
            if key not in seen and doc_id:
                seen.add(key)
                unique_citations.append(c)

        if not unique_citations:
            return 0

        # Batch check for existing citations with these doc_id + chunk_id pairs
        existing_keys = await self._find_existing(unique_citations, get_doc_id, get_chunk_id)
        new_citations = [
            c for c in unique_citations
            if (get_doc_id(c), get_chunk_id(c)) not in existing_keys
        ]

        if not new_citations:
            logger.debug("All %d citations already persisted, skipping", len(unique_citations))
            return 0

        count = 0
        for c in new_citations:
            try:
                doc_id = get_doc_id(c)
                chunk_id = get_chunk_id(c)
                quote = get_quote(c)
                version_id = get_version_id(c)
                passage_id = get_passage_id(c)
                source_uri = get_source_uri(c)

                # Build lineage note as JSON for full traceability
                lineage = {
                    "chunk_id": chunk_id,
                    "passage_id": passage_id,
                    "version_id": version_id,
                    "source_uri": source_uri,
                    "query": query[:500] if query else "",
                }
                note_json = json.dumps(lineage, ensure_ascii=False)

                # Create Evidence record — MUST include source_ref_id (P0 invariant)
                evidence_id = str(uuid4())
                description = self._truncate(
                    f"RAG citation: {self._truncate(quote, 500)}", 2000
                )

                # P0: Resolve or create SourceRef for every evidence.
                # Evidence without source_ref_id FK is forbidden in RAG/retrieval.
                source_ref_id = await self._resolve_source_ref(
                    source_uri=source_uri,
                    doc_id=doc_id,
                )

                await self.session.execute(
                    text(
                        "INSERT INTO evidences (id, description, evidence_level, "
                        "source_ref_id, source_passage_id, creator_id, is_deleted) "
                        "VALUES (:id, :description, :evidence_level, "
                        ":source_ref_id, :source_passage_id, :creator_id, false)"
                    ),
                    {
                        "id": evidence_id,
                        "description": description,
                        "evidence_level": EvidenceLevel.LEVEL_3.name,
                        "source_ref_id": source_ref_id,
                        "source_passage_id": passage_id if passage_id else None,
                        "creator_id": self.creator_id,
                    },
                )

                # Create Citation record
                citation_id = str(uuid4())
                await self.session.execute(
                    text(
                        "INSERT INTO citations (id, target_type, target_id, evidence_id, "
                        "quote_text, note, is_deleted) "
                        "VALUES (:id, :target_type, :target_id, :evidence_id, "
                        ":quote_text, :note, false)"
                    ),
                    {
                        "id": citation_id,
                        "target_type": "document",
                        "target_id": doc_id,
                        "evidence_id": evidence_id,
                        "quote_text": self._truncate(quote, 2000),
                        "note": note_json,
                    },
                )
                count += 1
            except Exception:
                logger.exception(
                    "Failed to persist citation doc_id=%s chunk_id=%s",
                    get_doc_id(c),
                    get_chunk_id(c),
                )
                continue

        if count > 0:
            await self.session.flush()
            logger.info("Persisted %d new citations (out of %d unique inline citations)", count, len(unique_citations))

        return count

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    async def _find_existing(
        self,
        citations: list,
        get_doc_id,
        get_chunk_id,
    ) -> set[tuple[str, str]]:
        """Find which (doc_id, chunk_id) pairs already have citation records.

        We check by scanning the note JSON field for chunk_id, since the Citation
        model itself doesn't have a direct chunk_id column.
        """
        existing: set[tuple[str, str]] = set()

        # Build list of chunk_ids to search for in note field
        chunk_ids = [get_chunk_id(c) for c in citations if get_chunk_id(c)]
        if not chunk_ids:
            return existing

        # Query: find citations where note contains one of our chunk_ids
        # Use target_type='document' to narrow the search
        result = await self.session.execute(
            text(
                "SELECT target_id, note FROM citations "
                "WHERE is_deleted=false AND target_type='document'"
            )
        )
        for row in result:
            target_id, note_str = row
            if not note_str:
                continue
            try:
                note = json.loads(note_str)
                cid = note.get("chunk_id", "")
                if cid:
                    existing.add((target_id, cid))
            except (json.JSONDecodeError, TypeError):
                continue

        return existing

    async def _resolve_source_ref(
        self,
        *,
        source_uri: str,
        doc_id: str,
    ) -> str | None:
        """Resolve or create a SourceRef for the given source URI and document.

        P0 invariant: every Evidence that enters RAG must have source_ref_id set.
        If a SourceRef already exists for this URL, reuse it.
        If a SourceRef exists for this document, reuse it.
        Otherwise create one.
        Returns None only if source_uri and doc_id are both empty (unlikely in
        practice — caller should handle).
        """
        # 1. Try by URL
        if source_uri:
            result = await self.session.execute(
                text(
                    "SELECT id FROM source_refs WHERE url=:url AND is_deleted=false LIMIT 1"
                ),
                {"url": source_uri},
            )
            row = result.fetchone()
            if row:
                return row[0]

        # 2. Try by page_location (document:<doc_id>)
        if doc_id:
            result = await self.session.execute(
                text(
                    "SELECT id FROM source_refs WHERE page_location=:loc AND is_deleted=false LIMIT 1"
                ),
                {"loc": f"document:{doc_id}"},
            )
            row = result.fetchone()
            if row:
                return row[0]

        # 3. Create one if we have enough info
        if source_uri or doc_id:
            sr_id = str(uuid4())
            # Fetch document title if we have doc_id
            title = "未知文献"
            if doc_id:
                result = await self.session.execute(
                    text("SELECT title FROM documents WHERE id=:did"),
                    {"did": doc_id},
                )
                drow = result.fetchone()
                if drow:
                    title = drow[0]

            await self.session.execute(
                text(
                    "INSERT INTO source_refs (id, title, url, page_location, is_deleted) "
                    "VALUES (:id, :title, :url, :loc, false)"
                ),
                {
                    "id": sr_id,
                    "title": title,
                    "url": source_uri or "",
                    "loc": f"document:{doc_id}" if doc_id else "",
                },
            )
            logger.info("Auto-created SourceRef %s for doc=%s url=%s", sr_id[:12], doc_id, source_uri[:60] if source_uri else "N/A")
            return sr_id

        return None

    @staticmethod
    def _truncate(s: str, max_len: int) -> str:
        """Truncate string to max_len, ellipsizing if needed."""
        if not s:
            return ""
        if len(s) <= max_len:
            return s
        return s[: max_len - 3] + "..."
